name: Build Calculator App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Build exe
      run: pyinstaller --onefile --noconsole calculator.py

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: calculator-exe
        path: dist/calculator.exe
        
